### ISSUE TITLE
breaks Logstash formatter.

### ISSUE THREAD

**Issue by i5okie** [dnsimple/lograge-tagged#3]
Looks like this gem breaks 
config.lograge.formatter = Lograge::Formatters::Logstash.new
or any other-than-default formatter configuration.

**Comment by weppos** [comment]
Currently it was only designed to work with the KeyValueFormatter.

https://github.com/dnsimple/lograge-tagged/blob/master/lib/lograge_tagged.rb#L18-L19

Feel free to provide a PR. Also feel free to add some stacktrace that could be used for debugging.
